### PR TITLE
a

### PR DESCRIPTION
**Pull request by samh065819**
i hate how nginx looks uppercase it hurts my eyes so much please change it im begging you its ofr my own mental health and eye health just merg ethe pull request

### CODE REVIEW

**Review by SuperEvilLuke — APPROVED** [review]

**Comment by samh065819** [comment]
merge the request

**Comment by samh065819** [comment]
do it

**Comment by samh065819** [comment]
now

**Comment by samh065819** [comment]
i am begging you

**Comment by samh065819** [comment]
thank you

**Pull request merged**
